### ISSUE TITLE
Clarification 

### ISSUE THREAD

**Issue by dpbasha** [IngmarStein/unifi-sonos-doc#10]
I have a rather large home that is fully covered by a UnFi system on the latest version.  I have a couple of questions below that I could use some guidance with.

1. If you had a choice between 2.4 WiFi and SonosNet, what would you prefer to use?
2. If I use SonosNet the way Sonos recommends, that is all wireless vs. all wired hardware, how robust is the SonosNet coverage and meshing capability.  In other words, would the hardware need to spaced in such a way to improve this coverage?
3. If all wireless or all wired hardware is used, do any of the UnFi changes mentioned in your article still need to be made?
4. If SonoNet is used, will the SSID showup during a WiFi scan?

Your help with these questions will be greatly appreciated.

**Comment by dpbasha** [comment]
Is someone able to help me with my questions?

**Comment by IngmarStein** [comment]
I've deleted your duplicate post in the other issue.

1. Existing WiFi because SonosNet creates interference and STP issues
2. You mean "the way Ubiquitu" recommends? All wired = no SonosNet. All wireless = no SonosNet except for legacy speakers.
3. Read https://github.com/IngmarStein/unifi-sonos-doc/?tab=readme-ov-file#recommended-settings again: "You can use the following settings […] to mix wired an wireless Sonos devices"
4. The SSID is hidden. You can probably measure it using tools like Wifi Explorer (see also: https://en.community.sonos.com/advanced-setups-229000/identifying-sonos-network-using-wifi-scanning-tools-6797651)

You probably get better engagement on your questions on https://en.community.sonos.com or https://www.reddit.com/r/sonos (related: https://www.reddit.com/r/sonos/comments/uurey4/wifi_vs_sonosnet/)

**Comment by dpbasha** [comment]
Thanks for your reply and closing the original post.

To be clear, if all WiFi is used and there is no mixing, there are not any special WiFi setting needed in UnFi, correct?

David Basha
***@***.******@***.***>
Click Here to Send Me Files Securely<https://complycrypt.complyauto.com/p/permalink/22c0462c-b11c-41ea-95d8-6dc799669af5?type=email>
cell: 678-570-2734
fax: 678-868-2251


***@***.***?anonymous&ep=signature>
Book time to meet with ***@***.***?anonymous&ep=signature>
